apiVersion: v1
kind: Service
metadata:
  name: sky-journey-ui-service
  namespace: core
spec:
  type: NodePort
  selector:
    app: sky-journey-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
