apiVersion: v1
kind: Service
metadata:
  name: sky-journey-core-service
  namespace: core
spec:
  type: NodePort
  selector:
    app: sky-journey-core
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
