apiVersion: v1
kind: Service
metadata:
  name: sky-journey-dbadmin-service
  namespace: dbadmin
spec:
  selector:
    app: sky-journey-dbadmin
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8081
  type: NodePort
