apiVersion: v1
kind: Service
metadata:
  name: sky-journey-auth-service
spec:
  type: NodePort
  selector:
    app: sky-journey-auth
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
