# Use the official MongoDB image
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Set the MongoDB data directory
VOLUME [ "/data/db" ]

# Run MongoDB using the default command
CMD ["mongod"]
