apiVersion: v1
kind: Service
metadata:
  name: sky-journey-db-service
spec:
  type: ClusterIP
  selector:
    app: sky-journey-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
