apiVersion: v1
kind: Service
metadata:
  name: sky-journey-payment-service
spec:
  type: NodePort
  selector:
    app: sky-journey-payment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
