apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-clusterrole
rules:
  - apiGroups: [""]
    resources:
      [
        "nodes",
        "namespaces",
        "pods",
        "services",
        "deployments",
        "replicasets",
        "storageclasses",
        "endpoints",
        "events",
      ]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
