apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sky-journey-portainer
subjects:
  - kind: ServiceAccount
    name: portainer-sa
    namespace: portainer
roleRef:
  kind: ClusterRole
  name: portainer-clusterrole
  apiGroup: rbac.authorization.k8s.io
