apiVersion: v1
kind: Service
metadata:
  name: sky-journey-portainer-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30779
  selector:
    app: sky-journey-portainer
